### ISSUE TITLE
Error: Form Input requires a name property when used

### ISSUE THREAD

**Issue by erifranck** [christianalfoni/formsy-react#331]
when reload my app in url where my component is render show this message  
```
Error: Form Input requires a name property when used
   at [object Object].componentWillMount (/home/erifranck/4geeks/mall4g-public/node_modules/formsy-react/lib/Mixin.js:67:13)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactCompositeComponent.js:210:12)
   at [object Object].wrapper [as mountComponent] (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactPerf.js:66:21)
   at Object.ReactReconciler.mountComponent (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactReconciler.js:37:35)
   at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactMultiChild.js:241:44)
   at ReactDOMComponent.Mixin._createContentMarkup (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactDOMComponent.js:591:32)
   at ReactDOMComponent.Mixin.mountComponent (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactDOMComponent.js:479:29)
   at Object.ReactReconciler.mountComponent (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactReconciler.js:37:35)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactCompositeComponent.js:225:34)
   at [object Object].wrapper [as mountComponent] (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactPerf.js:66:21)
   at Object.ReactReconciler.mountComponent (/home/erifranck/4geeks/mall4g-public/node_modules/react/lib/ReactReconciler.js:37:35)
```

 my code is here 

Inputs.js

```jsx
import React from "react";
import Formsy from 'formsy-react';

export default React.createClass({

    mixins: [Formsy.Mixin],
    
    getDefaultProps(){
      return {
        name : "one"
      }

    },

    changeValue(event) {
      this.setValue(event.currentTarget.value);
    },

    render() {
      const className = this.showRequired() ? 'required' : this.showError() ? 'error' : null;
      const errorMessage = this.getErrorMessage();
      const {styles,type,placeholder,name,maxlength} = this.props;

      return (
        <div className={className}>
          <input name={name} type={type} styles={styles} 
            placeholder={placeholder} 
            maxlength={maxlength}
            onChange={this.changeValue}
            value={this.getValue()}
          />
          <span>{errorMessage}</span>
        </div>
      )
  }
})
```

myform

```jsx
import React from "react";
import tree from "../../stores/tree";
import {key} from "../../helpers/stripeConfig";
import Customfield from './Inputs'
import axios from "axios";
import Formsy from 'formsy-react';
export default React.createClass({
  
  getInitialState() {
    return {
      canSubmit: false
    }
  },
  enableButton() {
    this.setState({
      canSubmit: true
    });
  },
  disableButton() {
    this.setState({
      canSubmit: false
    });
  },
  mapInputs(inputs) {
    return {
      'number': inputs.target,
      'exp_month': inputs.month,
      'exp_year': inputs.year,
      'cvc': inputs.cvc,
      'name': inputs.name,
      'address': inputs.address
    };
  },
  _checkout(model){

    const { number, exp_month, exp_year, cvc, name, address} = model;
    const { cart } = tree.get();
    const total = cart.reduce((a, b) => a + parseInt(b.price_no_tax) * parseInt(b.amount), 0);
    Stripe.setPublishableKey("pk_test_6X4xQJeYi234Uo15rLWMflbi");
    Stripe.card.createToken({
      number: number,
      exp_month: exp_month,
      exp_year: exp_year,
      cvc: cvc
    }, function(status, response) {
      if (status == 200) axios({
        url : "http://api.mall4g.com/api/orders",
        method: "POST",
        params : {
          stripe_token: response.id,
          amount: total,
          sender_person_name: name
        }

      })
        .then(() => this.refs.form.reset())
        .catch((res) => console.log())
    });
  
  },
  getDefaultStyles(){
    const {styles} = this.props;
    return {
      inputs:{
        marginLeft: 5,
        ...styles.inputs
      },
      container:{
        marginBottom: 10,
        ...styles.container
      },
      button:{
        ...styles.button
      }
    }

  },
  render() {
    const {buttonClasses}  = this.props;
    const styles = this.getDefaultStyles();
    
    return (
        <section >
          <div className="container" styles={styles.container} refs="form" mapping={this.mapInputs}>
            <Formsy.Form onValidSubmit={this._checkout} onValid={this.enableButton} onInvalid={this.disableButton}>
              <Customfield name="name" type="text" placeholder="Nombre"  styles={styles.inputs} ref="name"  required/>
              <Customfield name="address" type="text" placeholder="Direccion"  styles={styles.inputs}  ref="address" required/>
              <Customfield name="target" type="number" placeholder="target number"  styles={styles.inputs} maxlength="10" ref="number"  validations="isNumeric,isLength:10" required/>
              <Customfield name="month" type="number" placeholder="exp month"  styles={styles.inputs} ref="exp_month" validations="isNumeric,isLength:2" required/>
              <Customfield name="year" type="number" placeholder="exp year"  styles={styles.inputs} ref="exp_year" validations="isNumeric,isLength:4" required/>
              <Customfield name="cvc" type="text" placeholder="CVC"  styles={styles.inputs} ref="cvc" validations="isNumeric,isLength:3" required/>
              <button className={buttonClasses} disabled={!this.state.canSubmit} type="submit"> Submit</button>
            </Formsy.Form>
          </div>
        </section>
    )
  }
});

```

**Comment by Semigradsky** [comment]
```jsx
<div className="container" styles={styles.container} refs="form" mapping={this.mapInputs}>
```

`refs="form"` and `mapping` must be on `Formsy.Form`element

**Comment by erifranck** [comment]
thank :+1: i didn't see this error XD
