### ISSUE TITLE
Problem running examples

### ISSUE THREAD

**Issue by eriklharper** [christianalfoni/formsy-react#80]
Not a huge deal, but thought I'd log it anyway.  I pulled down the latest from master, ran `npm install` and then `npm run examples` from the root, and this is what I get:
```
npm run examples

> formsy-react@0.10.1 examples /x/vendor/christianalfoni/formsy-react
> webpack-dev-server --config examples/webpack.config.js --content-base examples


module.js:340
    throw err;
          ^
Error: Cannot find module 'examples/webpack.config.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/x/vendor/christianalfoni/formsy-react/node_modules/webpack/bin/convert-argv.js:56:12)
    at Object.<anonymous> (/x/vendor/christianalfoni/formsy-react/node_modules/webpack-dev-server/bin/webpack-dev-server.js:46:48)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! formsy-react@0.10.1 examples: `webpack-dev-server --config examples/webpack.config.js --content-base examples`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the formsy-react@0.10.1 examples script.
npm ERR! This is most likely a problem with the formsy-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config examples/webpack.config.js --content-base examples
npm ERR! You can get their info via:
npm ERR!     npm owner ls formsy-react
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/opt/boxen/nodenv/versions/v0.10.21/bin/npm" "run" "examples"
npm ERR! cwd /x/vendor/christianalfoni/formsy-react
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /x/vendor/christianalfoni/formsy-react/npm-debug.log
npm ERR! not ok code 0
```

I checked and made sure the `examples/webpack.config.js` file was present and it is, so I'm not sure what is up here.

**Comment by Semigradsky** [comment]
Try clear npm cache and before installing dependencies:
```
rm -rf node_modules
npm cache clean
npm install
npm run examples
```
If it is not helped try update your node.js and npm.

**Comment by eriklharper** [comment]
Thanks that helped.  After running through those commands I did see this as a result:

```
npm run examples

> formsy-react@0.10.1 examples /x/vendor/christianalfoni/formsy-react
> webpack-dev-server --config examples/webpack.config.js --content-base examples

http://localhost:8080/webpack-dev-server/
webpack result is served from /__build__/
content is served from /x/vendor/christianalfoni/formsy-react/examples
Hash: c274df21ee4ed4697d54
Version: webpack 1.8.4
Time: 299ms
    Asset     Size  Chunks             Chunk Names
 login.js  78.4 kB    0, 1  [emitted]  login
shared.js  8.59 kB       1  [emitted]  shared.js
chunk    {0} login.js (login) 21.4 kB {1} [rendered]
    [0] ./examples/login/app.js 2.4 kB {0} [built] [1 error]
    [1] ./src/main.js 11 kB {0} [built] [1 error]
    [2] ./src/validationRules.js 1.97 kB {0} [built]
    [3] ./src/utils.js 2.21 kB {0} [built]
    [4] ./src/Mixin.js 3.77 kB {0} [built]
chunk    {1} shared.js (shared.js) 0 bytes [rendered]

ERROR in ./examples/login/app.js
Module not found: Error: Cannot resolve module 'react' in /x/vendor/christianalfoni/formsy-react/examples/login
 @ ./examples/login/app.js 1:12-28

ERROR in ./src/main.js
Module not found: Error: Cannot resolve module 'react' in /x/vendor/christianalfoni/formsy-react/src
 @ ./src/main.js 1:28-44
webpack: bundle is now VALID.
```

I resolved it by simply doing `npm install react`.  Might be a good idea to update the examples Readme to include the step of installing react.  It worked for me after that.  Thanks!

**Comment by Semigradsky** [comment]
Hmm, strange, maybe this is determined by the fact that `react` is [peerDependency](https://github.com/christianalfoni/formsy-react/blob/master/package.json#L37). I could not repeat.

**Comment by eriklharper** [comment]
Yeah, that's definitely why.

**Comment by christianalfoni** [comment]
@Semigradsky, maybe add it with a pull to explain how to run the examples? As mentioned in #79. Would be really great, thanks for contributing! :-)

**Comment by Semigradsky** [comment]
I think it will not be superfluous :)
